on: workflow_dispatch
name: Publish Docs
permissions:
  contents: write
  pages: write
  pull-requests: write
jobs:
  reusable:
    uses: joshorr/workflows/.github/workflows/py-publish-docs.yml@main
    secrets: inherit
